apiVersion: apps/v1
kind: Deployment
metadata:
  name: soemi-woers
spec:
  selector:
    matchLabels:
      soemi-woers: soemi-woers
  replicas: 1
  template:
    metadata:
      labels:
        soemi-woers: soemi-woers
    spec:
      containers:
        - name: soemi-woers
          image: local/soemi-woers:latest
          ports:
            - containerPort: 8089
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8089
            initialDelaySeconds: 15
            timeoutSeconds: 1
