apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soemi-woers-ingress
  annotations:
    ingressClassName: "k8s.io/ingress-nginx"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: soemi-woers
                port:
                  number: 8089
