apiVersion: apps/v1
kind: Deployment
metadata:
  name: soemi-woeb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soemi-woeb
  template:
    metadata:
      labels:
        app: soemi-woeb
    spec:
      containers:
        - name: soemi-woeb
          image: z100/soemi-woeb:$IMAGE_TAG
          ports:
            - containerPort: 3000
