apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soemi-woeb-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: xn--smi-weather-rfb.ch
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: soemi-woeb
                port:
                  number: 3000
          - path: /api
            pathType: Exact
            backend:
              service:
                name: soemi-woers
                port:
                  number: 8089
