apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soemi-woeb-ingress
spec:
  rules:
    - host: localhost
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: soemi-woeb
                port:
                  number: 3000
