apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soemi-woeb-ingress
spec:
  rules:
    - http:
        paths:
          - path: soeminetes-dns-axl0alut.hcp.germanywestcentral.azmk8s.io
            pathType: Exact
            backend:
              service:
                name: soemi-woeb
                port:
                  number: 3000
